version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    tty: true
    env_file:
      - ./docker/mysql/.mysql.env
    
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./docker/mysql/init
        target: /docker-entrypoint-initdb.d
    ports:
      - 3306:3306
volumes:
  mysql-data:
    name: mysql-volume