name: Deploy client

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Setup AWS Amplify CLI
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
          source ~/.bashrc
          source ~/.bash_profile
          npm install -g @aws-amplify/cli
      # see: https://github.com/actions/setup-node/issues/32#issuecomment-539794249
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - run: |
          if test -n '${{ secrets.GH_PAGES_BASE_PATH }}'; then
            CLIENT_BASE_PATH='${{ secrets.GH_PAGES_BASE_PATH }}'
          else
            CLIENT_BASE_PATH="/$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
          fi
          echo "CLIENT_BASE_PATH=$CLIENT_BASE_PATH" >> $GITHUB_ENV
      - uses: actions/cache@v2
        id: client-npm-cache
        with:
          path: 'node_modules'
          key: client-npm-${{ hashFiles('yarn.lock') }}
      - run: yarn install
        if: steps.client-npm-cache.outputs.cache-hit != 'true'
      - name: Setup Amplify with headless mode
        run: sh ./amplify/init.sh prod ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} ~/.npm-global/bin
      - run: yarn run build:client
        env:
          API_ORIGIN: ${{ secrets.API_ORIGIN }}
          API_BASE_PATH: ${{ secrets.API_BASE_PATH }}
          NEXT_PUBLIC_ASSET_ORIGIN_URL: ${{ secrets.NEXT_PUBLIC_ASSET_ORIGIN_URL }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
