name: Deploy server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Setup AWS Amplify CLI
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          export PATH=~/.npm-global/bin:$PATH
          source ~/.profile
          source ~/.bashrc
          source ~/.bash_profile
          npm install -g @aws-amplify/cli
      # see: https://github.com/actions/setup-node/issues/32#issuecomment-539794249
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.API_DEPLOY_SSH_KEY }}
          name: id_rsa
          # If known_hosts needs to be set, use this.
          known_hosts: ${{ secrets.API_DEPLOY_KNOWN_HOSTS }}
      # TODO: apply this if we need to add amplify to backend
      # - name: Setup Amplify with headless mode
      #   run: sh ./amplify/init.sh prod ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} ~/.npm-global/bin
      - run: |
          npm install -g pm2@^4.5.1
          npx pm2 deploy production setup || true
          npx pm2 deploy production update
        env:
          API_DEPLOY_USER: ${{ secrets.API_DEPLOY_USER }}
          API_DEPLOY_HOST: ${{ secrets.API_DEPLOY_HOST }}
          API_DEPLOY_REPO: https://github.com/${{ github.repository }}.git
          API_DATABASE_URL: ${{ secrets.API_DATABASE_URL }}
          API_JWT_SECRET: ${{ secrets.API_JWT_SECRET }}
          API_USER_ID: ${{ secrets.API_USER_ID }}
          API_USER_PASS: ${{ secrets.API_USER_PASS }}
          API_ORIGIN: ${{ secrets.API_ORIGIN }}
          API_BASE_PATH: ${{ secrets.API_BASE_PATH }}
          API_SERVER_PORT: ${{ secrets.API_SERVER_PORT }}
          API_UPLOAD_DIR: ${{ secrets.API_UPLOAD_DIR }}
